name: BwManager
version: '${version}'
main: cn.xor7.xiaohei.bwmanager.BwManager
load: POSTWORLD
depend: [ BedWars1058, Parties ]
commands:
  bwteam:
    description:
    usage: /bwteam <[team-id]|list|info>
  bwcfg:
    description:
    usage: /bwcfg reload
  bwgame:
    description:
    usage: /bwgame <start|stop> <arena> <teamId1> <teamId2> [teamId3...]