name: BwManager
version: '${version}'
main: cn.xor7.xiaohei.bwmanager.BwManager
load: POSTWORLD
depend: [ BedWars1058, Parties ]
commands:
  bwteam:
    permission: bwmanager.command.bwteam
  bwcfg:
    permission: bwmanager.command.bwcfg
  bwgame:
    permission: bwmanager.command.bwgame
  bwspe:
    permission: bwmanager.command.bwspe